// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iMO6cGdFvRpu4fg_QgAPa_OcQufkBao',
    appId: '1:5491488236:web:5f9b76fbcd9a72cbf7bcc9',
    messagingSenderId: '5491488236',
    projectId: 'assignment2-aa425',
    authDomain: 'assignment2-aa425.firebaseapp.com',
    storageBucket: 'assignment2-aa425.appspot.com',
    measurementId: 'G-WZ7P16N37S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACJ4j9zpRjpXtpRs2CQsEt73KB6VhICM8',
    appId: '1:5491488236:android:a8e038314739ffa2f7bcc9',
    messagingSenderId: '5491488236',
    projectId: 'assignment2-aa425',
    storageBucket: 'assignment2-aa425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwnZAcHdVtRXbE1XrxxDDwjfM8z4O2tT0',
    appId: '1:5491488236:ios:26471e016d419e53f7bcc9',
    messagingSenderId: '5491488236',
    projectId: 'assignment2-aa425',
    storageBucket: 'assignment2-aa425.appspot.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwnZAcHdVtRXbE1XrxxDDwjfM8z4O2tT0',
    appId: '1:5491488236:ios:26471e016d419e53f7bcc9',
    messagingSenderId: '5491488236',
    projectId: 'assignment2-aa425',
    storageBucket: 'assignment2-aa425.appspot.com',
    iosBundleId: 'com.example.assignment2',
  );
}
